controllers:
  resource:
    path: ../src/*/UI/Controller/
    namespace: App
  type: attribute

legacy_controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
